//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductos
    {
        public int idProducto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string cantidad { get; set; }
        public string marca { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int idCategoria { get; set; }
        public bool esActivo { get; set; }
        public string unidadMedida { get; set; }
    
        public virtual tblCategorias tblCategorias { get; set; }
    }
}
